/**
 * Gen 1 map names in map-id order, generated from pokered
 * constants/map_constants.asm (names are facts about the game).
 */
export const GEN1_MAP_NAMES: string[] = [
  'Pallet Town',
  'Viridian City',
  'Pewter City',
  'Cerulean City',
  'Lavender Town',
  'Vermilion City',
  'Celadon City',
  'Fuchsia City',
  'Cinnabar Island',
  'Indigo Plateau',
  'Saffron City',
  'Unused Map 0b',
  'Route 1',
  'Route 2',
  'Route 3',
  'Route 4',
  'Route 5',
  'Route 6',
  'Route 7',
  'Route 8',
  'Route 9',
  'Route 10',
  'Route 11',
  'Route 12',
  'Route 13',
  'Route 14',
  'Route 15',
  'Route 16',
  'Route 17',
  'Route 18',
  'Route 19',
  'Route 20',
  'Route 21',
  'Route 22',
  'Route 23',
  'Route 24',
  'Route 25',
  'Reds House 1f',
  'Reds House 2f',
  'Blues House',
  'Oaks Lab',
  'Viridian Pokecenter',
  'Viridian Mart',
  'Viridian School House',
  'Viridian Nickname House',
  'Viridian Gym',
  'Digletts Cave Route 2',
  'Viridian Forest North Gate',
  'Route 2 Trade House',
  'Route 2 Gate',
  'Viridian Forest South Gate',
  'Viridian Forest',
  'Museum 1f',
  'Museum 2f',
  'Pewter Gym',
  'Pewter Nidoran House',
  'Pewter Mart',
  'Pewter Speech House',
  'Pewter Pokecenter',
  'Mt Moon 1f',
  'Mt Moon B1f',
  'Mt Moon B2f',
  'Cerulean Trashed House',
  'Cerulean Trade House',
  'Cerulean Pokecenter',
  'Cerulean Gym',
  'Bike Shop',
  'Cerulean Mart',
  'Mt Moon Pokecenter',
  'Cerulean Trashed House Copy',
  'Route 5 Gate',
  'Underground Path Route 5',
  'Daycare',
  'Route 6 Gate',
  'Underground Path Route 6',
  'Underground Path Route 6 Copy',
  'Route 7 Gate',
  'Underground Path Route 7',
  'Underground Path Route 7 Copy',
  'Route 8 Gate',
  'Underground Path Route 8',
  'Rock Tunnel Pokecenter',
  'Rock Tunnel 1f',
  'Power Plant',
  'Route 11 Gate 1f',
  'Digletts Cave Route 11',
  'Route 11 Gate 2f',
  'Route 12 Gate 1f',
  'Bills House',
  'Vermilion Pokecenter',
  'Pokemon Fan Club',
  'Vermilion Mart',
  'Vermilion Gym',
  'Vermilion Pidgey House',
  'Vermilion Dock',
  'Ss Anne 1f',
  'Ss Anne 2f',
  'Ss Anne 3f',
  'Ss Anne B1f',
  'Ss Anne Bow',
  'Ss Anne Kitchen',
  'Ss Anne Captains Room',
  'Ss Anne 1f Rooms',
  'Ss Anne 2f Rooms',
  'Ss Anne B1f Rooms',
  'Unused Map 69',
  'Unused Map 6a',
  'Unused Map 6b',
  'Victory Road 1f',
  'Unused Map 6d',
  'Unused Map 6e',
  'Unused Map 6f',
  'Unused Map 70',
  'Lances Room',
  'Unused Map 72',
  'Unused Map 73',
  'Unused Map 74',
  'Unused Map 75',
  'Hall Of Fame',
  'Underground Path North South',
  'Champions Room',
  'Underground Path West East',
  'Celadon Mart 1f',
  'Celadon Mart 2f',
  'Celadon Mart 3f',
  'Celadon Mart 4f',
  'Celadon Mart Roof',
  'Celadon Mart Elevator',
  'Celadon Mansion 1f',
  'Celadon Mansion 2f',
  'Celadon Mansion 3f',
  'Celadon Mansion Roof',
  'Celadon Mansion Roof House',
  'Celadon Pokecenter',
  'Celadon Gym',
  'Game Corner',
  'Celadon Mart 5f',
  'Game Corner Prize Room',
  'Celadon Diner',
  'Celadon Chief House',
  'Celadon Hotel',
  'Lavender Pokecenter',
  'Pokemon Tower 1f',
  'Pokemon Tower 2f',
  'Pokemon Tower 3f',
  'Pokemon Tower 4f',
  'Pokemon Tower 5f',
  'Pokemon Tower 6f',
  'Pokemon Tower 7f',
  'Mr Fujis House',
  'Lavender Mart',
  'Lavender Cubone House',
  'Fuchsia Mart',
  'Fuchsia Bills Grandpas House',
  'Fuchsia Pokecenter',
  'Wardens House',
  'Safari Zone Gate',
  'Fuchsia Gym',
  'Fuchsia Meeting Room',
  'Seafoam Islands B1f',
  'Seafoam Islands B2f',
  'Seafoam Islands B3f',
  'Seafoam Islands B4f',
  'Vermilion Old Rod House',
  'Fuchsia Good Rod House',
  'Pokemon Mansion 1f',
  'Cinnabar Gym',
  'Cinnabar Lab',
  'Cinnabar Lab Trade Room',
  'Cinnabar Lab Metronome Room',
  'Cinnabar Lab Fossil Room',
  'Cinnabar Pokecenter',
  'Cinnabar Mart',
  'Cinnabar Mart Copy',
  'Indigo Plateau Lobby',
  'Copycats House 1f',
  'Copycats House 2f',
  'Fighting Dojo',
  'Saffron Gym',
  'Saffron Pidgey House',
  'Saffron Mart',
  'Silph Co 1f',
  'Saffron Pokecenter',
  'Mr Psychics House',
  'Route 15 Gate 1f',
  'Route 15 Gate 2f',
  'Route 16 Gate 1f',
  'Route 16 Gate 2f',
  'Route 16 Fly House',
  'Route 12 Super Rod House',
  'Route 18 Gate 1f',
  'Route 18 Gate 2f',
  'Seafoam Islands 1f',
  'Route 22 Gate',
  'Victory Road 2f',
  'Route 12 Gate 2f',
  'Vermilion Trade House',
  'Digletts Cave',
  'Victory Road 3f',
  'Rocket Hideout B1f',
  'Rocket Hideout B2f',
  'Rocket Hideout B3f',
  'Rocket Hideout B4f',
  'Rocket Hideout Elevator',
  'Unused Map Cc',
  'Unused Map Cd',
  'Unused Map Ce',
  'Silph Co 2f',
  'Silph Co 3f',
  'Silph Co 4f',
  'Silph Co 5f',
  'Silph Co 6f',
  'Silph Co 7f',
  'Silph Co 8f',
  'Pokemon Mansion 2f',
  'Pokemon Mansion 3f',
  'Pokemon Mansion B1f',
  'Safari Zone East',
  'Safari Zone North',
  'Safari Zone West',
  'Safari Zone Center',
  'Safari Zone Center Rest House',
  'Safari Zone Secret House',
  'Safari Zone West Rest House',
  'Safari Zone East Rest House',
  'Safari Zone North Rest House',
  'Cerulean Cave 2f',
  'Cerulean Cave B1f',
  'Cerulean Cave 1f',
  'Name Raters House',
  'Cerulean Badge House',
  'Unused Map E7',
  'Rock Tunnel B1f',
  'Silph Co 9f',
  'Silph Co 10f',
  'Silph Co 11f',
  'Silph Co Elevator',
  'Unused Map Ed',
  'Unused Map Ee',
  'Trade Center',
  'Colosseum',
  'Unused Map F1',
  'Unused Map F2',
  'Unused Map F3',
  'Unused Map F4',
  'Loreleis Room',
  'Brunos Room',
  'Agathas Room',
]
