// GENERATED by scripts/gen-form-changes.py - do not hand-edit.
// Regenerate from a pokeemerald-expansion decomp when it changes.

export interface FormChangeParam {
  label: string
  kind?: 'item' | 'move' | 'ability' | 'species' | 'weather' | 'type' | 'status'
}

export interface FormChangeMethod {
  name: string
  label: string
  /** param1..param4, in order; absent entries are unused. */
  params: (FormChangeParam | null)[]
  description: string
}

/** `struct FormChange` is six u16s. */
export const FORM_CHANGE_ENTRY = 12
/** method 0 ends a table. */
export const FORM_CHANGE_TERMINATOR = 0

export const GEN3_FORM_CHANGES: Record<number, FormChangeMethod> = {
  1: { name: "FORM_CHANGE_ITEM_HOLD", label: "Item hold", params: [{ label: "item to hold", kind: "item" }, { label: "ability to check for, optional", kind: "ability" }], description: "Form change that activates when the specified item is given to or taken from the selected Pok\u00e9mon. param1: item to hold. param2: ability to check for, optional." },
  2: { name: "FORM_CHANGE_ITEM_USE", label: "Item use", params: [{ label: "item to use", kind: "item" }, { label: "time of day to check, optional" }, { label: "illegal statuses to have, optional", kind: "status" }], description: "Form change that activates when the item is used on the selected Pok\u00e9mon. param1: item to use param2: time of day to check, optional. - DAY if Form change that activates in the daytime. - NIGHT if For" },
  3: { name: "FORM_CHANGE_MOVE", label: "Move", params: [{ label: "move to check for", kind: "move" }], description: "TODO: Form change that activates when the Pok\u00e9mon learns or forgets the move. param1: move to check for param2: - WHEN_LEARNED if Form change that activates when move is forgotten - WHEN_FORGOTTEN if " },
  4: { name: "FORM_CHANGE_WITHDRAW", label: "Withdraw", params: [], description: "Form change that activates when the Pok\u00e9mon is withdrawn from the PC or Daycare. - No parameters." },
  5: { name: "FORM_CHANGE_FAINT", label: "Faint", params: [], description: "Form change that activates when the Pok\u00e9mon faints, either in battle or in the overworld by poison. - No parameters." },
  6: { name: "FORM_CHANGE_BEGIN_BATTLE", label: "Begin battle", params: [{ label: "item to hold, optional", kind: "item" }, { label: "a move that will be replaced, optional", kind: "move" }, { label: "a new move to replace it with, optional", kind: "move" }], description: "Form change that activates when the Pok\u00e9mon is sent out at the beginning of a battle param1: item to hold, optional param2: a move that will be replaced, optional param3: a new move to replace it with" },
  7: { name: "FORM_CHANGE_END_BATTLE", label: "End battle", params: [{ label: "item to hold, optional", kind: "item" }, { label: "a move that will be replaced, optional", kind: "move" }, { label: "a new move to replace it with, optional", kind: "move" }], description: "Form change that activates at the end of a battle. If species is not specified and it's on the player's side, it will try to use the value saved in gBattleStruct->partyState[x][y].changedSpecies from " },
  8: { name: "FORM_CHANGE_END_BATTLE_ENVIRONMENT", label: "End environment", params: [{ label: "battle environment to check" }], description: "Form change that activates at the end of a battle based on the environment if it participated in the battle and hasn't fainted. Takes priority over FORM_CHANGE_END_BATTLE. param1: battle environment t" },
  9: { name: "FORM_CHANGE_BATTLE_SWITCH_OUT", label: "Switch out", params: [{ label: "(optional) ability to check", kind: "ability" }], description: "Form change that activates when the Pok\u00e9mon is switched out in battle. param1: (optional) ability to check" },
  10: { name: "FORM_CHANGE_BATTLE_SWITCH_IN", label: "Switch in", params: [{ label: "ability to check", kind: "ability" }], description: "Form change that activates when the Pok\u00e9mon is switched-in in battle. This form change happens before other abilities like Neutralizing Gas. param1: ability to check" },
  11: { name: "FORM_CHANGE_BATTLE_HP_PERCENT_TURN_END", label: "HP percent turn end", params: [{ label: "Ability to check", kind: "ability" }, { label: "HP comparer" }, { label: "HP percentage threshold" }, { label: "(optional) Minimum level to do form change" }], description: "Form change that activates when the Pok\u00e9mon's HP % passes a certain threshold. param1: Ability to check. param2: HP comparer - HP_HIGHER_THAN if the form triggers when the current HP is higher than th" },
  12: { name: "FORM_CHANGE_BATTLE_HP_PERCENT_SEND_OUT", label: "HP percent send out", params: [{ label: "Ability to check", kind: "ability" }, { label: "HP comparer" }, { label: "HP percentage threshold" }, { label: "(optional) Minimum level to do form change" }], description: "Form change that activates when the Pok\u00e9mon's HP % passes a certain threshold when sent out into battle. param1: Ability to check. param2: HP comparer - HP_HIGHER_THAN if the form triggers when the cu" },
  13: { name: "FORM_CHANGE_BATTLE_HP_PERCENT_DURING_MOVE", label: "HP percent during move", params: [{ label: "Ability to check", kind: "ability" }, { label: "HP comparer" }, { label: "HP percentage threshold" }, { label: "Move used", kind: "move" }], description: "Form change that activates when the Pok\u00e9mon's HP % passes a certain threshold when using a move. param1: Ability to check. param2: HP comparer - HP_HIGHER_THAN if the form triggers when the current HP" },
  14: { name: "FORM_CHANGE_BATTLE_MEGA_EVOLUTION_ITEM", label: "Mega evolution item", params: [{ label: "item to hold", kind: "item" }], description: "Form change that activates when the mon has the defined item. If it's on the player's side, it also requires ITEM_MEGA_RING in the user's bag and for the player to trigger it by pressing START before " },
  15: { name: "FORM_CHANGE_BATTLE_MEGA_EVOLUTION_MOVE", label: "Mega evolution move", params: [{ label: "move to have", kind: "move" }], description: "Form change that activates when the mon has the defined move. If it's on the player's side, it also requires ITEM_MEGA_RING in the user's bag and for the player to trigger it by pressing START before " },
  16: { name: "FORM_CHANGE_BATTLE_PRIMAL_REVERSION", label: "Primal reversion", params: [{ label: "item to hold", kind: "item" }], description: "Form change that activates automatically when entering battle with the specified item. If the item is a Red Orb, it uses the Omega Symbol for the animation and icon. Otherwise, it defaults to the Alph" },
  17: { name: "FORM_CHANGE_BATTLE_WEATHER", label: "Weather", params: [{ label: "weather to check", kind: "weather" }, { label: "(optional) revert if specified ability is lost", kind: "ability" }], description: "Form change that activates when a specific weather is set during battle. param1: weather to check param2: (optional) revert if specified ability is lost" },
  18: { name: "FORM_CHANGE_BATTLE_TURN_END", label: "Turn end", params: [{ label: "ability to check", kind: "ability" }], description: "Form change that activates automatically when the turn ends. param1: ability to check." },
  19: { name: "FORM_CHANGE_BATTLE_ULTRA_BURST", label: "Ultra burst", params: [{ label: "item to hold", kind: "item" }], description: "Form change that activates when the mon has the defined item. If it's on the player's side, it also requires for the player to trigger it by pressing START before selecting a move. param1: item to hol" },
  20: { name: "FORM_CHANGE_BATTLE_GIGANTAMAX", label: "Gigantamax", params: [], description: "Form change that activates when the mon Dynamaxes. - No parameters" },
  21: { name: "FORM_CHANGE_TIME_OF_DAY", label: "Time of day", params: [{ label: "time of day to check" }], description: "Form change that activates at a certain time of day in the overworld automatically. param1: time of day to check. - DAY if Form change that activates in the daytime. - NIGHT if Form change that activa" },
  22: { name: "FORM_CHANGE_ITEM_USE_MULTICHOICE", label: "Item use multichoice", params: [{ label: "multichoice list (starting at 0)" }], description: "Form change that depends on a multichoice (e.g. Rotom Catalog). param1: multichoice list (starting at 0)." },
  23: { name: "FORM_CHANGE_STATUS", label: "Status", params: [{ label: "status", kind: "status" }], description: "Form change that activates when inflicted with a specific status param1: status" },
  24: { name: "FORM_CHANGE_BATTLE_HIT_BY_MOVE_CATEGORY", label: "Hit by move category", params: [{ label: "ability", kind: "ability" }, { label: "move category to check", kind: "move" }], description: "Form change that activates after receiving an attack. param1: ability param2: move category to check" },
  25: { name: "FORM_CHANGE_BATTLE_HIT_BY_CONFUSION_SELF_DMG", label: "Hit by confusion self dmg", params: [{ label: "ability", kind: "ability" }], description: "Form change that activates after hitting itself in confusion. param1: ability" },
  26: { name: "FORM_CHANGE_BATTLE_TERASTALLIZATION", label: "Terastallization", params: [{ label: "tera type", kind: "type" }], description: "Form change that activates when terastallized as as a specific type param1: tera type" },
  27: { name: "FORM_CHANGE_DAYS_PASSED", label: "Days passed", params: [{ label: "amount of days" }], description: "Form change that activates at midnight after a certain amount of days has passed. Adding this form change will automatically make the countdown start as soon the Pok\u00e9mon changes into a species other t" },
  28: { name: "FORM_CHANGE_BATTLE_BEFORE_MOVE", label: "Before move", params: [{ label: "move to check", kind: "move" }, { label: "ability to check, optional", kind: "ability" }], description: "Form change that activates before using a move. param1: move to check param2: ability to check, optional" },
  29: { name: "FORM_CHANGE_BATTLE_AFTER_MOVE", label: "After move", params: [{ label: "move to check", kind: "move" }], description: "Form change that activates after using a move. param1: move to check" },
  30: { name: "FORM_CHANGE_BATTLE_BEFORE_MOVE_CATEGORY", label: "Before move category", params: [{ label: "move category to check", kind: "move" }, { label: "ability to check, optional", kind: "ability" }], description: "Form change that activates before using a specific move category. param1: move category to check param2: ability to check, optional" },
  31: { name: "FORM_CHANGE_OVERWORLD_WEATHER", label: "Overworld weather", params: [{ label: "weather to check", kind: "weather" }], description: "Form change that activates when overworld weather changes. param1: weather to check." },
  32: { name: "FORM_CHANGE_DEPOSIT", label: "Deposit", params: [], description: "Form change that activates when the Pok\u00e9mon is deposited into the PC or Daycare." },
  33: { name: "FORM_CHANGE_BEGIN_WILD_ENCOUNTER", label: "Begin wild encounter", params: [], description: "Form change for Minior, which appears unchanged when encountered in the wild" },
}
