// GENERATED by scripts/gen-species-flags.py - do not hand-edit.
// Regenerate from a pokeemerald-expansion decomp when it changes.

export interface SpeciesFlag {
  bit: number
  name: string
  label: string
}

/** One-bit flags, in bit order. */
export const GEN3_SPECIES_FLAGS: SpeciesFlag[] = [
  { bit: 0, name: "isRestrictedLegendary", label: "Restricted legendary" },
  { bit: 1, name: "isSubLegendary", label: "Sub legendary" },
  { bit: 2, name: "isMythical", label: "Mythical" },
  { bit: 3, name: "isUltraBeast", label: "Ultra beast" },
  { bit: 4, name: "isParadox", label: "Paradox" },
  { bit: 5, name: "isTotem", label: "Totem" },
  { bit: 6, name: "isMegaEvolution", label: "Mega evolution" },
  { bit: 7, name: "isPrimalReversion", label: "Primal reversion" },
  { bit: 8, name: "isUltraBurst", label: "Ultra burst" },
  { bit: 9, name: "isGigantamax", label: "Gigantamax" },
  { bit: 10, name: "isTeraForm", label: "Tera form" },
  { bit: 11, name: "isAlolanForm", label: "Alolan form" },
  { bit: 12, name: "isGalarianForm", label: "Galarian form" },
  { bit: 13, name: "isHisuianForm", label: "Hisuian form" },
  { bit: 14, name: "isPaldeanForm", label: "Paldean form" },
  { bit: 15, name: "cannotBeTraded", label: "Cannot be traded" },
  { bit: 19, name: "dexForceRequired", label: "Dex force required" },
  { bit: 20, name: "teachingType", label: "Teaching type" },
  { bit: 21, name: "isFrontierBanned", label: "Frontier banned" },
  { bit: 22, name: "isSkyBattleBanned", label: "Sky battle banned" },
]

/**
 * Bits that are NOT booleans and must survive a checkbox edit.
 * perfectIVCount is three bits wide inside the same word.
 */
export const GEN3_SPECIES_FLAG_PRESERVE_MASK = 0x00070000
