// GENERATED by scripts/gen-evo-conditions.py - do not hand-edit.
// Regenerate from a pokeemerald-expansion decomp when it changes.

export interface EvoCondition {
  name: string
  label: string
  /** How many of arg1..arg3 the game actually reads. */
  args: number
  /** What arg1 identifies, when it is an id rather than a number. */
  argKind?: 'item' | 'species' | 'move' | 'type'
  description: string
}

/** Terminates a condition list in the ROM. */
export const EVO_CONDITIONS_END = 39

export const GEN3_EVO_CONDITIONS: Record<number, EvoCondition> = {
  0: { name: "IF_GENDER", label: "Gender", args: 1, description: "The Pok\u00e9mon is of specific gender." },
  1: { name: "IF_TIME", label: "Time of day", args: 1, description: "It is currently the specific time of day." },
  2: { name: "IF_NOT_TIME", label: "Not time of day", args: 1, description: "It is NOT currently the specific time of day." },
  3: { name: "IF_MIN_FRIENDSHIP", label: "Friendship at least", args: 1, description: "The Pok\u00e9mon has the defined amount of Friendship." },
  4: { name: "IF_ATK_GT_DEF", label: "Attack > Defense", args: 0, description: "The Pok\u00e9mon's Attack is greater than its Defense stat." },
  5: { name: "IF_ATK_EQ_DEF", label: "Attack = Defense", args: 0, description: "The Pok\u00e9mon's Attack is equal to its Defense stat." },
  6: { name: "IF_ATK_LT_DEF", label: "Attack < Defense", args: 0, description: "The Pok\u00e9mon's Attack is lower than its Defense stat." },
  7: { name: "IF_HOLD_ITEM", label: "Holding item", args: 1, argKind: "item", description: "The Pok\u00e9mon is holding a specific item." },
  8: { name: "IF_PID_UPPER_MODULO_10_GT", label: "Pid upper modulo 10 gt", args: 1, description: "The Pok\u00e9mon's upper personality value's modulo by 10 is greater than the defined value." },
  9: { name: "IF_PID_UPPER_MODULO_10_EQ", label: "Pid upper modulo 10 eq", args: 1, description: "The Pok\u00e9mon's upper personality value's modulo by 10 is equal to the defined value." },
  10: { name: "IF_PID_UPPER_MODULO_10_LT", label: "Pid upper modulo 10 lt", args: 1, description: "The Pok\u00e9mon's upper personality value's modulo by 10 is lower or equal than the defined value." },
  11: { name: "IF_MIN_BEAUTY", label: "Beauty at least", args: 1, description: "The Pok\u00e9mon has the defined amount of Beauty." },
  12: { name: "IF_MIN_COOLNESS", label: "Coolness at least", args: 1, description: "The Pok\u00e9mon has the defined amount of Coolness." },
  13: { name: "IF_MIN_SMARTNESS", label: "Smartness at least", args: 1, description: "The Pok\u00e9mon has the defined amount of Smartness. (aka Cleverness in Gen6+)" },
  14: { name: "IF_MIN_TOUGHNESS", label: "Toughness at least", args: 1, description: "The Pok\u00e9mon has the defined amount of Toughness." },
  15: { name: "IF_MIN_CUTENESS", label: "Cuteness at least", args: 1, description: "The Pok\u00e9mon has the defined amount of Cuteness." },
  16: { name: "IF_SPECIES_IN_PARTY", label: "Species in party", args: 1, argKind: "species", description: "The party contains a Pok\u00e9mon of the specified species." },
  17: { name: "IF_IN_MAP", label: "In map", args: 1, description: "The player is currently in the specific map." },
  18: { name: "IF_IN_MAPSEC", label: "In map section", args: 1, description: "The player is currently in the specific map sector." },
  19: { name: "IF_KNOWS_MOVE", label: "Knows move", args: 1, argKind: "move", description: "The Pok\u00e9mon knows specific move." },
  20: { name: "IF_TRADE_PARTNER_SPECIES", label: "Trade partner species", args: 1, argKind: "species", description: "The Pok\u00e9mon is traded for a specific species." },
  21: { name: "IF_TYPE_IN_PARTY", label: "Type in party", args: 1, argKind: "type", description: "The party contains a Pok\u00e9mon of the specified type." },
  22: { name: "IF_WEATHER", label: "Weather", args: 1, description: "It is currently the specific weather in the current map." },
  23: { name: "IF_KNOWS_MOVE_TYPE", label: "Knows move of type", args: 1, argKind: "type", description: "The Pok\u00e9mon knows a move with a specific type." },
  24: { name: "IF_NATURE", label: "Nature", args: 1, description: "The Pok\u00e9mon has a specific nature." },
  25: { name: "IF_AMPED_NATURE", label: "Amped nature", args: 0, description: "The Pok\u00e9mon has one of the following natures: Hardy, Brave, Adamant, Naughty, Docile, Impish, Lax, Hasty, Jolly, Naive, Rash, Sassy, or Quirky." },
  26: { name: "IF_LOW_KEY_NATURE", label: "Low key nature", args: 0, description: "The Pok\u00e9mon has one of the following natures: Lonely, Bold, Relaxed, Timid, Serious, Modest, Mild, Quiet, Bashful, Calm, Gentle, or Careful." },
  27: { name: "IF_RECOIL_DAMAGE_GE", label: "Recoil damage ge", args: 1, description: "The Pok\u00e9mon suffered at least certain amount of non-fainting recoil damage." },
  28: { name: "IF_CURRENT_DAMAGE_GE", label: "Current damage ge", args: 1, description: "The Pok\u00e9mon has the specified difference of HP from its Max HP." },
  29: { name: "IF_CRITICAL_HITS_GE", label: "Critical hits ge", args: 1, description: "The Pok\u00e9mon performed the specified number of critical hits in one battle at least." },
  30: { name: "IF_USED_MOVE_X_TIMES", label: "Used move x times", args: 2, description: "The Pok\u00e9mon has used a move for at least X amount of times." },
  31: { name: "IF_DEFEAT_X_WITH_ITEMS", label: "Defeat x with items", args: 3, argKind: "species", description: "The Pok\u00e9mon defeated X amount of Pok\u00e9mon of the specified species that are holding the specified item." },
  32: { name: "IF_PID_MODULO_100_GT", label: "Pid modulo 100 gt", args: 1, description: "The Pok\u00e9mon's personality value's modulo by 100 is greater than the defined value." },
  33: { name: "IF_PID_MODULO_100_EQ", label: "Pid modulo 100 eq", args: 1, description: "The Pok\u00e9mon's personality value's modulo by 100 is equal than the defined value." },
  34: { name: "IF_PID_MODULO_100_LT", label: "Pid modulo 100 lt", args: 1, description: "The Pok\u00e9mon's personality value's modulo by 100 is lower than the defined value." },
  35: { name: "IF_MIN_OVERWORLD_STEPS", label: "Overworld steps at least", args: 1, description: "The Player has taken a specific amount of steps in the overworld with the Pok\u00e9mon following them or in the first slot of the party." },
  36: { name: "IF_BAG_ITEM_COUNT", label: "Bag item count", args: 2, argKind: "item", description: "The Player has the specific amount of an item in the bag. It then removes those items." },
  37: { name: "IF_REGION", label: "In region", args: 1, description: "The Player is in the specific region." },
  38: { name: "IF_NOT_REGION", label: "Not in region", args: 1, description: "The Player is NOT in the specific region." },
}
