/**
 * National dex species names (1-649) and ability names (1-164) covering
 * Gen 1-5, generated from the pokeemerald-expansion constants (names are
 * facts about the games). Used by the DS adapter, whose ROMs store names
 * in an encrypted text format not yet decoded.
 */
export const NATDEX_NAMES: string[] = [
  'Bulbasaur',
  'Ivysaur',
  'Venusaur',
  'Charmander',
  'Charmeleon',
  'Charizard',
  'Squirtle',
  'Wartortle',
  'Blastoise',
  'Caterpie',
  'Metapod',
  'Butterfree',
  'Weedle',
  'Kakuna',
  'Beedrill',
  'Pidgey',
  'Pidgeotto',
  'Pidgeot',
  'Rattata',
  'Raticate',
  'Spearow',
  'Fearow',
  'Ekans',
  'Arbok',
  'Pikachu',
  'Raichu',
  'Sandshrew',
  'Sandslash',
  'Nidoran F',
  'Nidorina',
  'Nidoqueen',
  'Nidoran M',
  'Nidorino',
  'Nidoking',
  'Clefairy',
  'Clefable',
  'Vulpix',
  'Ninetales',
  'Jigglypuff',
  'Wigglytuff',
  'Zubat',
  'Golbat',
  'Oddish',
  'Gloom',
  'Vileplume',
  'Paras',
  'Parasect',
  'Venonat',
  'Venomoth',
  'Diglett',
  'Dugtrio',
  'Meowth',
  'Persian',
  'Psyduck',
  'Golduck',
  'Mankey',
  'Primeape',
  'Growlithe',
  'Arcanine',
  'Poliwag',
  'Poliwhirl',
  'Poliwrath',
  'Abra',
  'Kadabra',
  'Alakazam',
  'Machop',
  'Machoke',
  'Machamp',
  'Bellsprout',
  'Weepinbell',
  'Victreebel',
  'Tentacool',
  'Tentacruel',
  'Geodude',
  'Graveler',
  'Golem',
  'Ponyta',
  'Rapidash',
  'Slowpoke',
  'Slowbro',
  'Magnemite',
  'Magneton',
  'Farfetchd',
  'Doduo',
  'Dodrio',
  'Seel',
  'Dewgong',
  'Grimer',
  'Muk',
  'Shellder',
  'Cloyster',
  'Gastly',
  'Haunter',
  'Gengar',
  'Onix',
  'Drowzee',
  'Hypno',
  'Krabby',
  'Kingler',
  'Voltorb',
  'Electrode',
  'Exeggcute',
  'Exeggutor',
  'Cubone',
  'Marowak',
  'Hitmonlee',
  'Hitmonchan',
  'Lickitung',
  'Koffing',
  'Weezing',
  'Rhyhorn',
  'Rhydon',
  'Chansey',
  'Tangela',
  'Kangaskhan',
  'Horsea',
  'Seadra',
  'Goldeen',
  'Seaking',
  'Staryu',
  'Starmie',
  'Mr Mime',
  'Scyther',
  'Jynx',
  'Electabuzz',
  'Magmar',
  'Pinsir',
  'Tauros',
  'Magikarp',
  'Gyarados',
  'Lapras',
  'Ditto',
  'Eevee',
  'Vaporeon',
  'Jolteon',
  'Flareon',
  'Porygon',
  'Omanyte',
  'Omastar',
  'Kabuto',
  'Kabutops',
  'Aerodactyl',
  'Snorlax',
  'Articuno',
  'Zapdos',
  'Moltres',
  'Dratini',
  'Dragonair',
  'Dragonite',
  'Mewtwo',
  'Mew',
  'Chikorita',
  'Bayleef',
  'Meganium',
  'Cyndaquil',
  'Quilava',
  'Typhlosion',
  'Totodile',
  'Croconaw',
  'Feraligatr',
  'Sentret',
  'Furret',
  'Hoothoot',
  'Noctowl',
  'Ledyba',
  'Ledian',
  'Spinarak',
  'Ariados',
  'Crobat',
  'Chinchou',
  'Lanturn',
  'Pichu',
  'Cleffa',
  'Igglybuff',
  'Togepi',
  'Togetic',
  'Natu',
  'Xatu',
  'Mareep',
  'Flaaffy',
  'Ampharos',
  'Bellossom',
  'Marill',
  'Azumarill',
  'Sudowoodo',
  'Politoed',
  'Hoppip',
  'Skiploom',
  'Jumpluff',
  'Aipom',
  'Sunkern',
  'Sunflora',
  'Yanma',
  'Wooper',
  'Quagsire',
  'Espeon',
  'Umbreon',
  'Murkrow',
  'Slowking',
  'Misdreavus',
  'Unown',
  'Wobbuffet',
  'Girafarig',
  'Pineco',
  'Forretress',
  'Dunsparce',
  'Gligar',
  'Steelix',
  'Snubbull',
  'Granbull',
  'Qwilfish',
  'Scizor',
  'Shuckle',
  'Heracross',
  'Sneasel',
  'Teddiursa',
  'Ursaring',
  'Slugma',
  'Magcargo',
  'Swinub',
  'Piloswine',
  'Corsola',
  'Remoraid',
  'Octillery',
  'Delibird',
  'Mantine',
  'Skarmory',
  'Houndour',
  'Houndoom',
  'Kingdra',
  'Phanpy',
  'Donphan',
  'Porygon2',
  'Stantler',
  'Smeargle',
  'Tyrogue',
  'Hitmontop',
  'Smoochum',
  'Elekid',
  'Magby',
  'Miltank',
  'Blissey',
  'Raikou',
  'Entei',
  'Suicune',
  'Larvitar',
  'Pupitar',
  'Tyranitar',
  'Lugia',
  'Ho Oh',
  'Celebi',
  'Treecko',
  'Grovyle',
  'Sceptile',
  'Torchic',
  'Combusken',
  'Blaziken',
  'Mudkip',
  'Marshtomp',
  'Swampert',
  'Poochyena',
  'Mightyena',
  'Zigzagoon',
  'Linoone',
  'Wurmple',
  'Silcoon',
  'Beautifly',
  'Cascoon',
  'Dustox',
  'Lotad',
  'Lombre',
  'Ludicolo',
  'Seedot',
  'Nuzleaf',
  'Shiftry',
  'Taillow',
  'Swellow',
  'Wingull',
  'Pelipper',
  'Ralts',
  'Kirlia',
  'Gardevoir',
  'Surskit',
  'Masquerain',
  'Shroomish',
  'Breloom',
  'Slakoth',
  'Vigoroth',
  'Slaking',
  'Nincada',
  'Ninjask',
  'Shedinja',
  'Whismur',
  'Loudred',
  'Exploud',
  'Makuhita',
  'Hariyama',
  'Azurill',
  'Nosepass',
  'Skitty',
  'Delcatty',
  'Sableye',
  'Mawile',
  'Aron',
  'Lairon',
  'Aggron',
  'Meditite',
  'Medicham',
  'Electrike',
  'Manectric',
  'Plusle',
  'Minun',
  'Volbeat',
  'Illumise',
  'Roselia',
  'Gulpin',
  'Swalot',
  'Carvanha',
  'Sharpedo',
  'Wailmer',
  'Wailord',
  'Numel',
  'Camerupt',
  'Torkoal',
  'Spoink',
  'Grumpig',
  'Spinda',
  'Trapinch',
  'Vibrava',
  'Flygon',
  'Cacnea',
  'Cacturne',
  'Swablu',
  'Altaria',
  'Zangoose',
  'Seviper',
  'Lunatone',
  'Solrock',
  'Barboach',
  'Whiscash',
  'Corphish',
  'Crawdaunt',
  'Baltoy',
  'Claydol',
  'Lileep',
  'Cradily',
  'Anorith',
  'Armaldo',
  'Feebas',
  'Milotic',
  'Castform Normal',
  'Castform Normal',
  'Shuppet',
  'Banette',
  'Duskull',
  'Dusclops',
  'Tropius',
  'Chimecho',
  'Absol',
  'Wynaut',
  'Snorunt',
  'Glalie',
  'Spheal',
  'Sealeo',
  'Walrein',
  'Clamperl',
  'Huntail',
  'Gorebyss',
  'Relicanth',
  'Luvdisc',
  'Bagon',
  'Shelgon',
  'Salamence',
  'Beldum',
  'Metang',
  'Metagross',
  'Regirock',
  'Regice',
  'Registeel',
  'Latias',
  'Latios',
  'Kyogre',
  'Groudon',
  'Rayquaza',
  'Jirachi',
  'Deoxys Normal',
  'Deoxys Normal',
  'Grotle',
  'Torterra',
  'Chimchar',
  'Monferno',
  'Infernape',
  'Piplup',
  'Prinplup',
  'Empoleon',
  'Starly',
  'Staravia',
  'Staraptor',
  'Bidoof',
  'Bibarel',
  'Kricketot',
  'Kricketune',
  'Shinx',
  'Luxio',
  'Luxray',
  'Budew',
  'Roserade',
  'Cranidos',
  'Rampardos',
  'Shieldon',
  'Bastiodon',
  'Burmy Plant',
  'Burmy Plant',
  'Wormadam Plant',
  'Mothim Plant',
  'Vespiquen',
  'Pachirisu',
  'Buizel',
  'Floatzel',
  'Cherubi',
  'Cherrim Overcast',
  'Cherrim Overcast',
  'Shellos West',
  'Gastrodon West',
  'Drifloon',
  'Drifblim',
  'Buneary',
  'Lopunny',
  'Mismagius',
  'Honchkrow',
  'Glameow',
  'Purugly',
  'Chingling',
  'Stunky',
  'Skuntank',
  'Bronzor',
  'Bronzong',
  'Bonsly',
  'Mime Jr',
  'Happiny',
  'Chatot',
  'Spiritomb',
  'Gible',
  'Gabite',
  'Garchomp',
  'Munchlax',
  'Riolu',
  'Lucario',
  'Hippopotas',
  'Hippowdon',
  'Skorupi',
  'Drapion',
  'Croagunk',
  'Toxicroak',
  'Carnivine',
  'Finneon',
  'Lumineon',
  'Mantyke',
  'Snover',
  'Abomasnow',
  'Weavile',
  'Magnezone',
  'Lickilicky',
  'Rhyperior',
  'Tangrowth',
  'Electivire',
  'Magmortar',
  'Togekiss',
  'Yanmega',
  'Leafeon',
  'Glaceon',
  'Gliscor',
  'Mamoswine',
  'Porygon Z',
  'Gallade',
  'Probopass',
  'Dusknoir',
  'Froslass',
  'Rotom',
  'Uxie',
  'Mesprit',
  'Azelf',
  'Dialga',
  'Palkia',
  'Heatran',
  'Regigigas',
  'Giratina Altered',
  'Giratina Altered',
  'Phione',
  'Manaphy',
  'Darkrai',
  'Shaymin Land',
  'Shaymin Land',
  'Arceus Normal',
  'Snivy',
  'Servine',
  'Serperior',
  'Tepig',
  'Pignite',
  'Emboar',
  'Oshawott',
  'Dewott',
  'Samurott',
  'Patrat',
  'Watchog',
  'Lillipup',
  'Herdier',
  'Stoutland',
  'Purrloin',
  'Liepard',
  'Pansage',
  'Simisage',
  'Pansear',
  'Simisear',
  'Panpour',
  'Simipour',
  'Munna',
  'Musharna',
  'Pidove',
  'Tranquill',
  'Unfezant',
  'Blitzle',
  'Zebstrika',
  'Roggenrola',
  'Boldore',
  'Gigalith',
  'Woobat',
  'Swoobat',
  'Drilbur',
  'Excadrill',
  'Audino',
  'Timburr',
  'Gurdurr',
  'Conkeldurr',
  'Tympole',
  'Palpitoad',
  'Seismitoad',
  'Throh',
  'Sawk',
  'Sewaddle',
  'Swadloon',
  'Leavanny',
  'Venipede',
  'Whirlipede',
  'Scolipede',
  'Cottonee',
  'Whimsicott',
  'Petilil',
  'Lilligant',
  'Basculin Red Striped',
  'Basculin Red Striped',
  'Krokorok',
  'Krookodile',
  'Darumaka',
  'Darmanitan Standard',
  'Darmanitan Standard',
  'Dwebble',
  'Crustle',
  'Scraggy',
  'Scrafty',
  'Sigilyph',
  'Yamask',
  'Cofagrigus',
  'Tirtouga',
  'Carracosta',
  'Archen',
  'Archeops',
  'Trubbish',
  'Garbodor',
  'Zorua',
  'Zoroark',
  'Minccino',
  'Cinccino',
  'Gothita',
  'Gothorita',
  'Gothitelle',
  'Solosis',
  'Duosion',
  'Reuniclus',
  'Ducklett',
  'Swanna',
  'Vanillite',
  'Vanillish',
  'Vanilluxe',
  'Deerling Spring',
  'Deerling Spring',
  'Sawsbuck Spring',
  'Karrablast',
  'Escavalier',
  'Foongus',
  'Amoonguss',
  'Frillish',
  'Jellicent',
  'Alomomola',
  'Joltik',
  'Galvantula',
  'Ferroseed',
  'Ferrothorn',
  'Klink',
  'Klang',
  'Klinklang',
  'Tynamo',
  'Eelektrik',
  'Eelektross',
  'Elgyem',
  'Beheeyem',
  'Litwick',
  'Lampent',
  'Chandelure',
  'Axew',
  'Fraxure',
  'Haxorus',
  'Cubchoo',
  'Beartic',
  'Cryogonal',
  'Shelmet',
  'Accelgor',
  'Stunfisk',
  'Mienfoo',
  'Mienshao',
  'Druddigon',
  'Golett',
  'Golurk',
  'Pawniard',
  'Bisharp',
  'Bouffalant',
  'Rufflet',
  'Braviary',
  'Vullaby',
  'Mandibuzz',
  'Heatmor',
  'Durant',
  'Deino',
  'Zweilous',
  'Hydreigon',
  'Larvesta',
  'Volcarona',
  'Cobalion',
  'Terrakion',
  'Virizion',
  'Tornadus Incarnate',
  'Tornadus Incarnate',
  'Thundurus Incarnate',
  'Zekrom',
  'Landorus Incarnate',
  'Landorus Incarnate',
  'Keldeo Ordinary',
  'Keldeo Ordinary',
  'Meloetta Aria',
]

export const NATDEX_ABILITIES: string[] = [
  'Stench',
  'Drizzle',
  'Speed Boost',
  'Battle Armor',
  'Sturdy',
  'Damp',
  'Limber',
  'Sand Veil',
  'Static',
  'Volt Absorb',
  'Water Absorb',
  'Oblivious',
  'Cloud Nine',
  'Compound Eyes',
  'Insomnia',
  'Color Change',
  'Immunity',
  'Flash Fire',
  'Shield Dust',
  'Own Tempo',
  'Suction Cups',
  'Intimidate',
  'Shadow Tag',
  'Rough Skin',
  'Wonder Guard',
  'Levitate',
  'Effect Spore',
  'Synchronize',
  'Clear Body',
  'Natural Cure',
  'Lightning Rod',
  'Serene Grace',
  'Swift Swim',
  'Chlorophyll',
  'Illuminate',
  'Trace',
  'Huge Power',
  'Poison Point',
  'Inner Focus',
  'Magma Armor',
  'Water Veil',
  'Magnet Pull',
  'Soundproof',
  'Rain Dish',
  'Sand Stream',
  'Pressure',
  'Thick Fat',
  'Early Bird',
  'Flame Body',
  'Run Away',
  'Keen Eye',
  'Hyper Cutter',
  'Pickup',
  'Truant',
  'Hustle',
  'Cute Charm',
  'Plus',
  'Minus',
  'Forecast',
  'Sticky Hold',
  'Shed Skin',
  'Guts',
  'Marvel Scale',
  'Liquid Ooze',
  'Overgrow',
  'Blaze',
  'Torrent',
  'Swarm',
  'Rock Head',
  'Drought',
  'Arena Trap',
  'Vital Spirit',
  'White Smoke',
  'Pure Power',
  'Shell Armor',
  'Air Lock',
  'Ability 77',
  'Motor Drive',
  'Rivalry',
  'Steadfast',
  'Snow Cloak',
  'Gluttony',
  'Anger Point',
  'Unburden',
  'Heatproof',
  'Simple',
  'Dry Skin',
  'Download',
  'Iron Fist',
  'Poison Heal',
  'Adaptability',
  'Skill Link',
  'Hydration',
  'Solar Power',
  'Quick Feet',
  'Normalize',
  'Sniper',
  'Magic Guard',
  'No Guard',
  'Stall',
  'Technician',
  'Leaf Guard',
  'Klutz',
  'Mold Breaker',
  'Super Luck',
  'Aftermath',
  'Anticipation',
  'Forewarn',
  'Unaware',
  'Tinted Lens',
  'Filter',
  'Slow Start',
  'Scrappy',
  'Storm Drain',
  'Ice Body',
  'Solid Rock',
  'Snow Warning',
  'Honey Gather',
  'Frisk',
  'Reckless',
  'Multitype',
  'Flower Gift',
  'Bad Dreams',
  'Ability 124',
  'Sheer Force',
  'Contrary',
  'Unnerve',
  'Defiant',
  'Defeatist',
  'Cursed Body',
  'Healer',
  'Friend Guard',
  'Weak Armor',
  'Heavy Metal',
  'Light Metal',
  'Multiscale',
  'Toxic Boost',
  'Flare Boost',
  'Harvest',
  'Telepathy',
  'Moody',
  'Overcoat',
  'Poison Touch',
  'Regenerator',
  'Big Pecks',
  'Sand Rush',
  'Wonder Skin',
  'Analytic',
  'Illusion',
  'Imposter',
  'Infiltrator',
  'Mummy',
  'Moxie',
  'Justified',
  'Rattled',
  'Magic Bounce',
  'Sap Sipper',
  'Prankster',
  'Sand Force',
  'Iron Barbs',
  'Zen Mode',
  'Victory Star',
  'Turboblaze',
  'Teravolt',
]
