"""
Generates the expansion's form-change table from the decomp.

Mega Evolution is not an evolution in this engine. It lives in a separate
per-species table:

    struct FormChange { u16 method, targetSpecies, param1..param4; };

so a Mega's trigger - which stone, which move - is invisible to anything
that only reads the evolution data.

The enum in constants/form_change_types.h documents each method's params
in the comment above it ("param1: item to hold."), so both the labels and
what each param MEANS are read from there rather than guessed. The kind
of a param (item, move, ability, ...) is taken from the words the comment
uses, which is what lets the editor show a stone by name instead of a
number.

Usage: python3 scripts/gen-form-changes.py <decomp-dir> > out.ts
"""
import re, sys, json

# Words in a param's description that identify what it refers to.
KINDS = [
    ('item', 'item'),
    ('move', 'move'),
    ('ability', 'ability'),
    ('species', 'species'),
    ('weather', 'weather'),
    ('type', 'type'),
    ('status', 'status'),
]


def kind_of(text):
    low = text.lower()
    # A parameter described as a STATUS_FIELD_* flag is a bitmask, not a
    # status condition; without this it matches 'status' and gets offered
    # a status dropdown it has no business having.
    if 'status_field' in low:
        return None
    for word, kind in KINDS:
        if word in low:
            return kind
    return None


def label_of(name):
    words = name[len('FORM_CHANGE_'):].replace('_', ' ').lower()
    words = words.replace('hp percent', 'HP percent').replace('battle ', '')
    return words[:1].upper() + words[1:]


root = sys.argv[1]
src = open(f'{root}/include/constants/form_change_types.h', encoding='utf-8').read()
block = re.search(r'enum FormChanges\s*\{(.*?)\n\};', src, re.S)
if not block:
    sys.exit('FormChanges enum not found')

entries = []
comment = []
value = 0
for line in block.group(1).split('\n'):
    stripped = line.strip()
    if stripped.startswith('//'):
        comment.append(stripped[2:].strip())
        continue
    m = re.match(r'(FORM_CHANGE_\w+)\s*,?', stripped)
    if not m:
        continue
    name = m.group(1)
    params = {}
    for c in comment:
        pm = re.match(r'param(\d):\s*(.+)', c)
        if pm:
            params[int(pm.group(1))] = pm.group(2).rstrip('.')
    entries.append((value, name, params, ' '.join(comment)))
    comment = []
    value += 1

print('// GENERATED by scripts/gen-form-changes.py - do not hand-edit.')
print('// Regenerate from a pokeemerald-expansion decomp when it changes.')
print('')
print('export interface FormChangeParam {')
print('  label: string')
print("  kind?: 'item' | 'move' | 'ability' | 'species' | 'weather' | 'type' | 'status'")
print('}')
print('')
print('export interface FormChangeMethod {')
print('  name: string')
print('  label: string')
print('  /** param1..param4, in order; absent entries are unused. */')
print('  params: (FormChangeParam | null)[]')
print('  description: string')
print('}')
print('')
print('/** `struct FormChange` is six u16s. */')
print('export const FORM_CHANGE_ENTRY = 12')
print('/** method 0 ends a table. */')
print('export const FORM_CHANGE_TERMINATOR = 0')
print('')
print('export const GEN3_FORM_CHANGES: Record<number, FormChangeMethod> = {')
for value, name, params, description in entries:
    if name == 'FORM_CHANGE_TERMINATOR':
        continue
    cells = []
    for i in (1, 2, 3, 4):
        if i not in params:
            cells.append('null')
            continue
        kind = kind_of(params[i])
        k = f", kind: {json.dumps(kind)}" if kind else ''
        cells.append('{ label: %s%s }' % (json.dumps(params[i]), k))
    while cells and cells[-1] == 'null':
        cells.pop()
    print(f'  {value}: {{ name: {json.dumps(name)}, label: {json.dumps(label_of(name))}, '
          f'params: [{", ".join(cells)}], description: {json.dumps(description[:200])} }},')
print('}')
sys.stderr.write(f'{len(entries) - 1} form-change methods\n')
