"""
Generates the species flags layout from the decomp's struct SpeciesInfo.

The struct ends with a u32 of one-bit booleans - isMegaEvolution,
isHisuianForm, isMythical and the rest - which is what tells a Mega form
apart from an ordinary species. They are declared in bit order, so their
positions are read off the declaration rather than counted by hand.

Two things the parser must respect:

  * perfectIVCount is three bits wide, not one. It is emitted so callers
    know which bits are NOT booleans and must be preserved on write;
    flipping a checkbox must never corrupt it.
  * padding fields are skipped, but still consume bits.

Usage: python3 scripts/gen-species-flags.py <decomp-dir> > out.ts
"""
import re, sys, json

root = sys.argv[1]
src = open(f'{root}/include/pokemon.h', encoding='utf-8').read()

struct = re.search(r'struct SpeciesInfo[^{]*\{(.*?)\n\};', src, re.S)
if not struct:
    sys.exit('struct SpeciesInfo not found')

flags = re.search(r'//\s*Flags\s*\n(.*?)(?=\n\s*//|\n\s*s8 )', struct.group(1), re.S)
if not flags:
    sys.exit('flags block not found')

bit = 0
rows = []
for line in flags.group(1).split('\n'):
    m = re.match(r'\s*u32\s+(\w+)\s*:\s*(\d+)\s*;', line.split('//')[0])
    if not m:
        continue
    name, width = m.group(1), int(m.group(2))
    if not name.startswith('padding'):
        rows.append((bit, name, width))
    bit += width

def label(name):
    # isMegaEvolution -> "Mega evolution"; cannotBeTraded -> "Cannot be traded"
    words = re.sub(r'(?<!^)(?=[A-Z])', ' ', name).lower()
    if words.startswith('is '):
        words = words[3:]
    return words[:1].upper() + words[1:]

print('// GENERATED by scripts/gen-species-flags.py - do not hand-edit.')
print('// Regenerate from a pokeemerald-expansion decomp when it changes.')
print('')
print('export interface SpeciesFlag {')
print('  bit: number')
print('  name: string')
print('  label: string')
print('}')
print('')
print('/** One-bit flags, in bit order. */')
print('export const GEN3_SPECIES_FLAGS: SpeciesFlag[] = [')
for b, name, width in rows:
    if width == 1:
        print(f'  {{ bit: {b}, name: {json.dumps(name)}, label: {json.dumps(label(name))} }},')
print(']')
print('')
print('/**')
print(' * Bits that are NOT booleans and must survive a checkbox edit.')
print(' * perfectIVCount is three bits wide inside the same word.')
print(' */')
mask = 0
for b, name, width in rows:
    if width > 1:
        mask |= ((1 << width) - 1) << b
print(f'export const GEN3_SPECIES_FLAG_PRESERVE_MASK = 0x{mask:08x}')
sys.stderr.write(f'{sum(1 for r in rows if r[2] == 1)} boolean flags, preserve mask 0x{mask:08x}\n')
