"""Names for the numbers scripts are full of.

A script argument is a bare number in the ROM: `setflag 0x11b` says
nothing, `setflag RECEIVED_CASTFORM` says everything. The names live in
the decomp, so they are extracted rather than transcribed - the same
rule as every other generated table here.

Four sources, each with its own shape:
  * flags.h / vars.h   - #defines, often written as an offset from a
    base (`(TEMP_VARS_START + 0x3)`), so values are resolved by
    evaluating each expression against the names already known.
  * data/specials.inc  - a `def_special` per line, numbered in order.
  * data/event_scripts.s - gStdScripts, again numbered in order.

Usage: python3 scripts/gen-script-symbols.py <decomp-dir> > out.ts
"""
import re, sys, json

root = sys.argv[1]


def defines(path):
    """#define NAME <expr> pairs, in file order."""
    out = []
    try:
        src = open(path, encoding='utf-8').read()
    except FileNotFoundError:
        return out
    for m in re.finditer(r'^#define\s+(\w+)\s+(.+?)\s*(?://.*)?$', src, re.M):
        out.append((m.group(1), m.group(2).strip()))
    return out


def resolve(pairs, prefix):
    """NAME -> number, for the names that are plain arithmetic.

    Values reference other names, so this repeats until nothing new
    resolves rather than assuming the file is in dependency order.
    """
    known, pending = {}, list(pairs)
    for _ in range(8):
        rest = []
        for name, expr in pending:
            if not re.fullmatch(r'[\w\s()+\-*x0-9A-Fa-f]+', expr):
                continue
            try:
                value = eval(expr, {'__builtins__': {}}, dict(known))  # noqa: S307
            except Exception:
                rest.append((name, expr))
                continue
            if isinstance(value, int):
                known[name] = value
        if len(rest) == len(pending):
            break
        pending = rest
    # Several names can share a value (aliases, and unused slots named
    # after their neighbours). The first definition is the canonical one.
    # Several names can share a value (aliases, and the stubs that
    # define the other game's flags as 0). The first definition is the
    # canonical one, and 0 is dropped: neither flags nor vars start
    # there, so anything landing on it is a stub.
    out = {}
    for name, value in known.items():
        if name.startswith(prefix) and value != 0:
            out.setdefault(value, name[len(prefix):])
    return out


def ordered(path, pattern, prefix=''):
    """Names numbered by the order they appear, e.g. def_special lines."""
    out = {}
    for i, m in enumerate(re.finditer(pattern, open(f'{root}/{path}', encoding='utf-8'). read(), re.M)):
        out[i] = prefix + m.group(1)
    return out


# flags.h counts its trainer flags from the trainer ids, so the headers
# it includes have to be resolved alongside it. The _frlg headers are
# left out on purpose: the two files define each other's names as 0 so
# that whichever game is not being built compiles away, and mixing them
# would hand those stubs the id 0.
flags = resolve(sum((defines(f'{root}/include/constants/{f}.h') for f in
                     ('trainers', 'opponents', 'rematches', 'flags')), []), 'FLAG_')
variables = resolve(defines(f'{root}/include/constants/vars.h'), 'VAR_')
specials = ordered('data/specials.inc', r'^\s*def_special\s+(\w+)')
# gStdScripts is one list among many .4byte runs; keep only the block
# that follows the gStdScripts label.
src = open(f'{root}/data/event_scripts.s', encoding='utf-8').read()
block = src.split('gStdScripts::', 1)[1].split('gStdScripts_End', 1)[0]
stds = {i: m.group(1) for i, m in enumerate(re.finditer(r'^\s*\.4byte\s+Std_(\w+)', block, re.M))}


def table(name, mapping, doc):
    print(f'\n/** {doc} */')
    print(f'export const {name}: Record<number, string> = {{')
    for k in sorted(mapping):
        print(f'  {k}: {json.dumps(mapping[k])},')
    print('}')


print('// GENERATED by scripts/gen-script-symbols.py - do not hand-edit.')
print('// Regenerate from a pokeemerald-expansion decomp when it changes.')
print('// Prefixes (FLAG_, VAR_, Std_) are stripped: the editor adds back')
print('// whatever context the field it is shown in needs.')
table('GEN3_FLAG_NAMES', flags, 'Story/progress flags, by number.')
table('GEN3_VAR_NAMES', variables, 'Script variables, by number (0x4000 and up).')
table('GEN3_SPECIAL_NAMES', specials, 'Native functions callable with `special`, in table order.')
table('GEN3_STD_SCRIPTS', stds, 'The standard scripts `callstd` runs, in table order.')
print(f'\n// flags {len(flags)}, vars {len(variables)}, specials {len(specials)}, std {len(stds)}',
      file=sys.stderr)
