"""
Generates the expansion's evolution-condition table from the decomp.

pokeemerald-expansion collapsed the ~40 classic evolution methods into
nine and moved everything else into a list of conditions hanging off each
evolution:

    struct EvolutionParam { u16 condition; u16 arg1, arg2, arg3; };

So Golbat evolves by EVO_LEVEL with param 0 - no level at all - and the
real requirement is IF_MIN_FRIENDSHIP in its condition list. An editor
showing only the method and param shows a meaningless 0.

Names and descriptions come from the enum in constants/pokemon.h. How
many arguments a condition actually uses is not written down anywhere,
so it is read from the evaluator in src/pokemon.c: the highest argN the
case block touches is the count. Conditions that test the Pokemon itself
(IF_ATK_GT_DEF, IF_AMPED_NATURE) reference none and take no arguments.

Usage: python3 scripts/gen-evo-conditions.py <decomp-dir> > out.ts
"""
import re, sys, json

# What arg1 means, where it is an id rather than a plain number. Only
# these get a dropdown in the UI; everything else is a number.
ARG_KINDS = {
    'IF_HOLD_ITEM': 'item',
    'IF_BAG_ITEM_COUNT': 'item',
    'IF_SPECIES_IN_PARTY': 'species',
    'IF_TRADE_PARTNER_SPECIES': 'species',
    'IF_DEFEAT_X_WITH_ITEMS': 'species',
    'IF_KNOWS_MOVE': 'move',
    'IF_TYPE_IN_PARTY': 'type',
    'IF_KNOWS_MOVE_TYPE': 'type',
}


def conditions(root):
    src = open(f'{root}/include/constants/pokemon.h', encoding='utf-8').read()
    block = re.search(r'enum EvolutionConditions\s*\{(.*?)\}', src, re.S)
    if not block:
        sys.exit('EvolutionConditions enum not found')
    out = []
    for line in block.group(1).split('\n'):
        m = re.match(r'\s*(IF_\w+|CONDITIONS_END)\s*,?\s*(?://\s*(.*))?$', line)
        if m:
            out.append((m.group(1), (m.group(2) or '').strip()))
    return out


def arg_counts(root):
    """Highest argN each case block references in the evaluator."""
    src = open(f'{root}/src/pokemon.c', encoding='utf-8').read()
    counts = {}
    cases = list(re.finditer(r'case\s+(IF_\w+):', src))
    for i, m in enumerate(cases):
        end = cases[i + 1].start() if i + 1 < len(cases) else min(len(src), m.end() + 2000)
        body = src[m.end():end]
        used = [int(a) for a in re.findall(r'\.arg(\d)\b', body)]
        counts[m.group(1)] = max(used) if used else 0
    return counts


def label(name, comment):
    """A short human label: 'IF_MIN_FRIENDSHIP' -> 'Friendship at least'."""
    words = name[3:].lower().replace('_', ' ')
    fixes = {
        'min friendship': 'Friendship at least',
        'min beauty': 'Beauty at least',
        'min coolness': 'Coolness at least',
        'min smartness': 'Smartness at least',
        'min toughness': 'Toughness at least',
        'min cuteness': 'Cuteness at least',
        'min overworld steps': 'Overworld steps at least',
        'atk gt def': 'Attack > Defense',
        'atk eq def': 'Attack = Defense',
        'atk lt def': 'Attack < Defense',
        'hold item': 'Holding item',
        'knows move': 'Knows move',
        'knows move type': 'Knows move of type',
        'species in party': 'Species in party',
        'type in party': 'Type in party',
        'not time': 'Not time of day',
        'time': 'Time of day',
        'in mapsec': 'In map section',
        'in map': 'In map',
        'not region': 'Not in region',
        'region': 'In region',
    }
    return fixes.get(words, words[:1].upper() + words[1:])


root = sys.argv[1]
enum = conditions(root)
counts = arg_counts(root)

print('// GENERATED by scripts/gen-evo-conditions.py - do not hand-edit.')
print('// Regenerate from a pokeemerald-expansion decomp when it changes.')
print('')
print('export interface EvoCondition {')
print('  name: string')
print('  label: string')
print('  /** How many of arg1..arg3 the game actually reads. */')
print('  args: number')
print("  /** What arg1 identifies, when it is an id rather than a number. */")
print("  argKind?: 'item' | 'species' | 'move' | 'type'")
print('  description: string')
print('}')
print('')
value = 0
end_value = None
rows = []
for name, comment in enum:
    if name == 'CONDITIONS_END':
        end_value = value
        break
    rows.append((value, name, comment))
    value += 1

print(f'/** Terminates a condition list in the ROM. */')
print(f'export const EVO_CONDITIONS_END = {end_value}')
print('')
print('export const GEN3_EVO_CONDITIONS: Record<number, EvoCondition> = {')
for v, name, comment in rows:
    kind = ARG_KINDS.get(name)
    kind_s = f", argKind: {json.dumps(kind)}" if kind else ''
    print(f'  {v}: {{ name: {json.dumps(name)}, label: {json.dumps(label(name, comment))}, '
          f'args: {counts.get(name, 1)}{kind_s}, description: {json.dumps(comment)} }},')
print('}')
sys.stderr.write(f'{len(rows)} conditions, CONDITIONS_END = {end_value}\n')
